# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", path: "setup.sh"
  # config.ssh.insert_key = false
end
